### ISSUE TITLE
Incomplete player list in response with fake clients in game

### ISSUE THREAD

**Issue by toorisrael** [yourmnbbn/smext-fakequeries#2] opened 2021-11-24 14:01 UTC
Hi again!
You should change [this](https://github.com/yourmnbbn/smext-fakequeries/blob/main/natives.cpp#L187):
`int maxClients = g_pServer->GetNumClients();`
to
`int maxClients = g_pServer->GetNumClients()+g_pServer->GetNumFakeClients();`
to fix missing real players in query when bots disconnect (you can easily reproduce this bug with "bot_quota_mode fill" and than joining team).

**Comment by yourmnbbn** [comment] 2021-11-24 14:44
Hey, thanks a lot for the feedback! It seems that both issue #1 and #2 is because I didn't take fake clients into account. These changes are reasonable. But may I ask why are they closed?

**Comment by toorisrael** [comment] 2021-11-24 17:40
#1 It turns out "gpGlobals->curtime" is only counting since map start, so it's not a complete solution. There should be used something like:
`engine->Time()` but I can't get it to work (is hl2sdk-csgo missing [Time()](https://github.com/alliedmodders/hl2sdk/blob/csgo/public/eiface.h) function? [Valve](https://developer.valvesoftware.com/wiki/IVEngineServer), [sdk2013](https://github.com/alliedmodders/hl2sdk/blob/sdk2013/public/eiface.h#L222))
error: 'class IVEngineServer' has no member named 'Time'
I'm still new to this extensions stuff, so it's possible I just don't understand something.

You should also add challenge for A2S_INFO, as it was added in last CSGO update when server uses host_info_show 2.

Looks like FQ_SetNumFakeClients does nothing for me, real bot count is still shown in query (but I can't see any errors in code).

**Comment by yourmnbbn** [comment] 2021-11-24 18:53
Ah, you can get engine time by Plat_FloatTime, which was in hl2sdk. 

Challenge for A2S_INFO is in my to do list since the latest update. 

FQ_SetNumFakeClients really does nothing. It’s just a part of the protocol. This is only valid when you use third party a2s tools to get some extra information about the server which doesn’t show on the community server list in game. If you want to set the clients of the server, use FQ_SetNumClients. 

As for this issue, at first I just simply thought these are all about fake clients and probably you are right. But after reviewing the code I think the problem should not be the maxClients since GetNumClients returns the total client count including fake clients. So if this problem can be confirmed then it must be somewhere else that goes wrong. 

So these two issues are worth opening, and they should be fixed.

**Comment by toorisrael** [comment] 2021-11-24 20:11
Oh, I assumed 'Plat_FloatTime' will only work for NUCLEARDAWN engine looking on [SourceMod code](https://github.com/alliedmodders/sourcemod/blob/master/core/smn_halflife.cpp#L98), thanks for the tip, I will test it. EDIT: working, thanks.

I've tested FQ_SetNumFakeClients with [PHP Source Query](https://github.com/xPaw/PHP-Source-Query) and it looked like I said (no change in bot count).

About the 'GetNumClients': [leaked CSGO code](https://github.com/perilouswithadollarsign/cstrike15_src/blob/master/engine/baseserver.cpp#L1442)
I'm not sure if bots are considered connected, but still you may be right. EDIT: You're right, so there must be another problem.

For sure it's worth opening/fixing, my information was just incomplete.

**Comment by yourmnbbn** [comment] 2021-11-25 08:33
Commit 2759553 has fixed the incorrect connection time of fake clients. 

> I've tested FQ_SetNumFakeClients with PHP Source Query and it looked like I said (no change in bot count).

Confirmed the problem, I did have made a mistake implementing CReturnA2sInfo::GetNumFakeClients. Commit df3a46f has fixed this.

**Comment by toorisrael** [comment] 2021-11-25 14:46
OK, thanks.
For [GetMaxClients](https://github.com/yourmnbbn/smext-fakequeries/blob/main/natives.cpp#L545) I suggest using by default:
`g_pCvar->FindVar("sv_visiblemaxplayers")->GetInt()`
(I guess it was your intention anyway)
because it looks like GetMaxHumanPlayers() is just  '-maxplayers' or '-maxplayers_override' from server start command.

**Comment by yourmnbbn** [comment] 2021-11-25 15:04
> (I guess it was your intention anyway)
because it looks like GetMaxHumanPlayers() is just '-maxplayers' or '-maxplayers_override' from server start command.

Exactly.

All the new features and fixes are ready(#3). Just need more test before it could be merged.

**Comment by yourmnbbn** [comment] 2021-11-25 15:14
Can you help to confirm that commit 15e5d9e fixes this issue? In my test case it works fine. Thanks!

**Comment by toorisrael** [comment] 2021-11-25 20:31
Yes, now it's working fine.
Also, after testing server with php query I've found fields "SteamID" and "SpecPort" are missing from query response if your extension is in use.
And it looks like there is some problem with your A2S_INFO challenge implementation.

**Comment by yourmnbbn** [comment] 2021-11-26 03:58
SteamID and spectator port are both extra data. They are controlled by the extra data flag(EDF). EDF is not so important to me so I didn’t implement all. That’s why adding custom EDF support is in the to do list. But it’s already implemented in my private repo of this ,I didn’t take it here because it still has some problems. Ofc I can bring the changes here if it’s necessary, it’s what I have intended to do anyway, the problems are not complicated but I’m just too lazy :D

As for the A2S_INFO challenge, is there any unexpected behavior?

**Comment by toorisrael** [comment] 2021-11-26 07:47
Oh OK then, I didn't know what this "EDF" means.

So after CSGO update introducing A2S_INFO challenge, I've updated my sourcebans to support this (as I'm using some older version with many modifications) and it's working fine with clean server. After adding last version of your extension (this one with A2S changes) Sourcebans can't scan the server. Also, my hosting provider is using gameq to check if server is online - and again it's not working only if I use last version of your extension.

I can send you later some *.pcap packet dumps/differences.

**Comment by yourmnbbn** [comment] 2021-11-26 09:24
That's weird, I have tested challenge on both game community server list and one of the third party tools [python-a2s](https://github.com/Yepoleb/python-a2s), they all show the A2S_INFO response correctly. The A2S_INFO challenge is actually the same as AS2_PLAYER. So any debug file would be appreciated.

Commit 5705bde and a1b116c have added the hltv information and steamid in extra data of A2S_INFO.

**Comment by yourmnbbn** [comment] 2021-11-26 13:28
I think it’s probably because of this. 
https://github.com/yourmnbbn/smext-fakequeries/blob/a1b116cd24c5903aea2673aaf270463d71748ce7/extension.cpp#L87
Maybe the remote client has sent more than 29 bytes packet, and only the first 29 bytes are valid. So here the extension just mistakenly drop them, causing no response. But while the steam api handling the incoming packet, it might just verify the first 29 bytes and doesn’t care about the packet length, I suppose. This may explains why it doesn’t work for all but some of the tools. You can temporarily replace `recvSize == 25 || recvSize == 29` with  `recvSize >= 25` and give it a try.

**Comment by toorisrael** [comment] 2021-11-26 13:32
Thanks, I will test it soon.

I've found another bug. Most of real players don't get score updated in query.

**Comment by yourmnbbn** [comment] 2021-11-26 13:42
Oh thanks, I think I might know what causes this.  Are those valid scores correctly corresponding with the players?

**Comment by toorisrael** [comment] 2021-11-26 13:44
No, the score is wrong or not updated for long time (or maybe those with score were fakes, I didn't check).

**Comment by yourmnbbn** [comment] 2021-11-26 13:45
https://github.com/yourmnbbn/smext-fakequeries/blob/fa6296b2b417e7acad48aa377e7b8065706f5107/natives.cpp#L180
Replace `iClientIndex*4` with `iClientIndex`, I messed up with the memory here. It should work.

**Comment by toorisrael** [comment] 2021-11-26 13:49
Thanks, I will test all the fixes and let you know!

**Comment by toorisrael** [comment] 2021-11-26 14:14
Score is still not working, query seems to work.

**Comment by yourmnbbn** [comment] 2021-11-26 16:16
Commit 21e49f4 has fixed incorrect player score. It's been tested working.

Thanks a lot for all the feedback! I think all of the known problems have been fixed so far and the new features are ready. I'll leave the PR there for a few days before merging.

**Comment by toorisrael** [comment] 2021-11-26 16:54
I've got problem with some of my servers running on Debian 8 after your last score update:
https://crash.limetech.org/6ys6fnepb24l
I've compiled this on Debian 8 / gcc 4.9 for compatibility, (like always).

And here's compilation warning I haven't notice before:
/root/sm/extensions/fakequeries/natives.cpp: In member function 'bool CReturnA2sPlayer::GetPlayerStatus(int, PlayerInfo_t&)':
/root/sm/extensions/fakequeries/natives.cpp:150:82: warning: passing NULL to non-pointer argument 4 of 'virtual bool SourceMod::IGameConfigManager::LoadGameConfigFile(const char*, SourceMod::IGameConfig**, char*, size_t)' [-Wconversion-null]
         if(!gameconfs->LoadGameConfigFile("sm-cstrike.games", &cfg, nullptr, NULL))

**Comment by yourmnbbn** [comment] 2021-11-26 17:09
Got it. I’ll take a look tomorrow. I haven’t tested it on Linux. On windows it’s fine. I don’t know if it’s legal not passing error message buffer to LoadGameConfigFile function. You can try passing a buffer. I just supposed passing nullptr it will do nothing. I don’t want error messages spamming in log. But since this is official game data it’s not likely to fail getting the offset.

**Comment by toorisrael** [comment] 2021-11-26 17:50
Yeah I've already fixed that warning this way, but servers are still crashing (it probably had nothing to do with this).

For what I've tested:
Private server where only me can join - works fine
Public servers, after few players join - crash

EDIT:
After more testing - it will crash on every server after at least 2 real players connect.

**Comment by yourmnbbn** [comment] 2021-11-26 18:06
Can you give me the full access of the crash dump if it’s convenient? My steam id is 76561198303323332. If not, past the exception reason and the related raw stack here.

**Comment by toorisrael** [comment] 2021-11-26 18:10
Done.

**Comment by yourmnbbn** [comment] 2021-11-26 18:29
https://github.com/yourmnbbn/smext-fakequeries/blob/56b0220faa60ba67530c9e3d94505041dba45926/natives.cpp#L99
The crash is because pEntity is nullptr. So far I am not sure why is it nullptr. You can simply add this to avoid crash. 
```cpp
if(!pEntity)
{
    info.score = 0;
    return true;
}
```

**Comment by toorisrael** [comment] 2021-11-26 18:40
Thanks!

**Comment by toorisrael** [comment] 2021-11-26 19:24
It looks like it sometimes stop showing players score, but I need to test it more xD
Also about A2S_FIXES:
![image](https://user-images.githubusercontent.com/4301144/143623153-17e95839-5015-4f63-a7c7-1f20cf7192db.png)
I don't know why it still works fine for my private, test server, len is stil 29...
![image](https://user-images.githubusercontent.com/4301144/143623363-760e363c-a75c-49fb-9ee1-b18ac661d929.png)
EDIT:
OK, about showing score - ignore this, probably extension was not reloaded on this server.
And about this private server which is working fine with query - it had host_info_show 1, with 2 it doesn't work.
I guess changing this `if(recvSize == 25)` to `if(recvSize == 25 ||  recvSize == 29)` could be a temp fix for me.
EDIT2: and it's not xD Maybe this can help:
len 29:
![image](https://user-images.githubusercontent.com/4301144/143624236-07db62d4-9336-4e05-9aac-199f5b81371d.png)
len 25:
![image](https://user-images.githubusercontent.com/4301144/143624263-95ddd2cf-c9fe-4e6c-822f-5db7e1790f29.png)

**Comment by yourmnbbn** [comment] 2021-11-27 02:26
Is this 29 bytes packet handled by the extension? If it is, there might be something wrong with the sourceban challenge implementation. The extra 4 bytes added to tail should be the challenge number got from the server. 
https://github.com/yourmnbbn/smext-fakequeries/blob/fa6296b2b417e7acad48aa377e7b8065706f5107/challenge.cpp#L43-L46
In extension the challenge is randomly generated and it’s not possible to be 0xFFFFFFFF. So no responding is likely because the challenge verification failed. 

Challenge can’t be 0 because in A2S_PLAYER, the community server list in game skip sending challenge request, instead it directly send request with challenge 0, so as to make a difference the challenge is not allowed to be 0. And challenge with -1 becomes the challenge request frame, then there will be infinite request.  Since the A2S_INFO and A2S_PLAYER uses the same challenge manager in extension, they have the same challenge generating rules. And the rules are not the problem of no responding. As far as I can tell sourceban just have sent an invalid challenge number which will never be generated in the extension.

**Comment by yourmnbbn** [comment] 2021-11-27 03:57
There is also another explanation to this. The expected progress of A2S_INFO challenge is first 25 bytes request, 9 bytes response by server with challenge, then 29 bytes request with challenge, finally the full info response. As is shown in your screenshot the PHP tool goes as expected. For sourceban, if no packets were missing, seems to directly send request with challenge -1. I’m not sure if this is also a fast request just like the A2S_PLAYER request with challenge 0 according to my last explanation. If the sourceban works fine this way without extension, then we have the solution. 

When adding challenge for info I thought there will be a fast request just as player request. Normally the fast request is used officially and it is not mentioned in valve’s documentation. Apparently they are not using fast request in csgo for now, but maybe they have implemented.

**Comment by toorisrael** [comment] 2021-11-27 06:33
There are 2 ways A2S_INFO will work on non-modified CSGO server with host_info_show 2:
1) We're sending A2S_INFO without challenge, server responds with challenge, we send A2S_INFO with challenge, server responds with info/data
![image](https://user-images.githubusercontent.com/4301144/143670969-17ca31a3-6ebf-4ccb-982c-e00dca2998f3.png)

2) We're sending A2S_INFO with FF FF FF FF challenge, server responds with challenge, we send A2S_INFO with challenge, server responds with info/data:
![image](https://user-images.githubusercontent.com/4301144/143670869-4f68a96e-afa9-4309-87b1-35b9f5693a33.png)

Correct me if I'm wrong. The 2) way is not handled by your extension, so I have no response when I use your extension.
I can easily fix this in my sourcebans which I agree it doesn't use the proper way, however there are still some scripts people use which won't work.

**Comment by yourmnbbn** [comment] 2021-11-27 06:48
Yeah, sending request with extra bytes is not the recommended way currently. However, in valve’s A2S_INFO documentation writes:

> NOTE: In the future, additional data may be appended to the request! Do not assume that if a request has extra data, that it is a bogus packet!

So it’s true that we can’t assume the length of the request always stays the same. I’ll make some adjustments later in the day. 

EDIT: Can you test directly sending request with false challenge and 0 instead of 0xFFFFFFFF to see if the server still response with challenge?

**Comment by toorisrael** [comment] 2021-11-27 07:27
Yeah, server still responds with challenge:
![image](https://user-images.githubusercontent.com/4301144/143672474-0d159833-033a-4711-89db-2304b7bd6651.png)

**Comment by yourmnbbn** [comment] 2021-11-27 07:35
Got it. Thanks! Looks like it only send full information to the request with correct challenge, otherwise it just keep responding with the challenge number.

**Comment by yourmnbbn** [comment] 2021-11-27 07:43
https://github.com/yourmnbbn/smext-fakequeries/blob/56b0220faa60ba67530c9e3d94505041dba45926/extension.cpp#L91
I think replace this with
```cpp
if(recvSize == 25 || !g_ReturnA2sInfo.IsValidRequest(buf))
```
And remove these lines should fix the problem. 
https://github.com/yourmnbbn/smext-fakequeries/blob/56b0220faa60ba67530c9e3d94505041dba45926/extension.cpp#L98-L99

**Comment by toorisrael** [comment] 2021-11-27 08:24
Well, that fixed issues for my sourcebans, but didn't fix for [gameq](url=https://github.com/Austinb/GameQ), which for example my hosting provider uses, eh... xD
This script must be broken in another way.
![image](https://user-images.githubusercontent.com/4301144/143674080-061cf3e4-dd05-40ec-9747-a1aa395ae881.png)

**Comment by yourmnbbn** [comment] 2021-11-27 08:45
0x56 is the header of A2S_RULES, which will not be handled in the extension. From the screen shot I suppose the remote client has sent the 25 bytes query, and expecting the direct info response, but it turned out to be the challenge frame which was unexpected. Then it just request other necessary information like A2S_RULES or something. 

So based on the current information it looks like your gameq doesn’t support challenge. 

If it does support challenge, You can try to monitor the packet without extension and then see what’s the differences between those progress.

**Comment by yourmnbbn** [comment] 2021-11-27 09:28
I don’t write PHP but I’ve looked at the [GameQ](https://github.com/Austinb/GameQ) project, don’t know if this is the version you use. It seems that the challenge for info is still not implemented. If you have implemented yourself I suggest checking all the progress to see if it fit the new protocol requirements.

**Comment by toorisrael** [comment] 2021-11-27 12:00
You're right, github version doesn't scan even non-modified server because it lacks challenge support for A2S_INFO. Probably my hosting provider modified gameq in a wrong way, so it works only for clean server, for now I can do nothing with this, but I've contacted them for more info. Thanks for all your help and great extension!

**Comment by yourmnbbn** [comment] 2021-11-27 18:34
Yeah, it’s actually not that easy to find the problem without the implementation detail, since it’s definitely not implemented in the way that the documentation suggests. However you can still try to find some clues while tracing those packets. 

I will also pay attention to this when doing the final test these days, but it’s not guaranteed that I can figure it out, really not much information about this issue. 

If you get the implementation detail or find some clues, welcome to open another issue about this. Although the implementation of your gameq may not be that proper, but still it works with clean server. So to me, this will definitely be a worthy fix.

**Comment by toorisrael** [comment] 2021-11-27 22:50
They use this: https://github.com/Austinb/GameQ/tree/v2
with this fix: https://github.com/Austinb/GameQ/pull/578/commits/a6438fdbae276b7b365608a8ce758ffcefdb33f4

![image](https://user-images.githubusercontent.com/4301144/143722529-caaf7522-4c73-4567-8f59-60e6868685af.png)
It works differently, if I understand correctly first query is asking for challenge, receives challenge, and sends A2S_INFO with challenge.

**Comment by yourmnbbn** [comment] 2021-11-28 05:12
Ah, well, this is tricky. [Here](https://github.com/Austinb/GameQ/blob/30ffe4077b47c4bc80f6ef628d18df845b03c7c9/gameq/protocols/source.php#L44) it got challenge with request `FF FF FF FF 56 00 00 00 00 `, which is a A2S_RULES challenge request. So the challenge number is got from the server. It's true that without extension the challenge only have to be requested once and then use it to send multiple requests with that number. But the extension has its own challenge generator, using server generated challenge will cause challenge verification failed. It may not be a good idea to have a separate challenge manager in extension.

**Comment by yourmnbbn** [comment] 2021-11-28 07:02
I did a small test using CBaseServer::GetChallengeNr trying to get the server's original chalenge but failed. This challenge remains unchanged. So it's not that easy to really figure out how challenges are generated by the server. So I've decided not to make changes for this in the coming version. 

To make gameq work, here is some of my advice:
1. Use host_info_show 1, and change [this](https://github.com/Austinb/GameQ/blob/30ffe4077b47c4bc80f6ef628d18df845b03c7c9/gameq/protocols/source.php#L46) to `\xFF\xFF\xFF\xFF\x55\x00\x00\x00\x00` will do a fast request for A2S_PLAYER without challenge, then everything will work.
2. Use host_info_show 2, and change [this](https://github.com/Austinb/GameQ/blob/30ffe4077b47c4bc80f6ef628d18df845b03c7c9/gameq/protocols/source.php#L44) to `\xFF\xFF\xFF\xFF\x55\xFF\xFF\xFF\xFF` will get the challenge generated by the extension, which will make A2S_INFO and A2S_PLAYER work but break A2S_RULES request. Then you can either ignore A2S_RULES or make a separate request for it.

EDIT: I've discovered that `\xFF\xFF\xFF\xFF\x55\x00\x00\x00\x00` in the clean server won't send the A2S_PLAYER response, may be I made a mistake or they have changed this. So this 'fast request' only works with this extension. I can also implement a fast request for A2S_INFO with challenge 0, which will help to make things easier for all the 3rd party tools with this extension.

**Comment by toorisrael** [comment] 2021-11-28 08:44
A2S_RULES is broken in CSGO as far is know, so it can be used just to get challange. Maybe you can cache last challenge per IP [like engine does](https://github.com/perilouswithadollarsign/cstrike15_src/blob/master/engine/baseserver.cpp#L2323) in future version?

**Comment by yourmnbbn** [comment] 2021-11-28 08:57
Good idea! This is not much work and I can implement it in the coming version.

**Comment by yourmnbbn** [comment] 2021-11-28 11:02
Commit 3bdb47e has implemented that. It's been tested on both linux and windows.

**Comment by toorisrael** [comment] 2021-11-29 13:10
Sadly it still doesn't work with GameQ mentioned [here](https://github.com/yourmnbbn/smext-fakequeries/issues/2#issuecomment-980802236).
![image](https://user-images.githubusercontent.com/4301144/143873930-99519cc5-7b9d-44a2-a5a8-3b9865cb2526.png)

**Comment by yourmnbbn** [comment] 2021-11-29 13:33
Yeah, that is not a fix for the gameq. The aim of that commit is to improve the extension’s challenge generating system. Still, the server challenge is different from the extension, using server generated challenge to request for a extension handled response will still cause challenge verification failing.

As I‘ve decided not to make a change for this currently, if you want to make both challenge and gameq work. You can do as what I have suggested [here](https://github.com/yourmnbbn/smext-fakequeries/issues/2#issuecomment-980851125) if you don’t care about the A2A_RULES.

Maybe in the not far future I will add an option to let users decide whether to use the server’s challenge system or the extension’s. But that requires figuring out how server challenge is generated and how to implement that by reverse engineering, which takes time. But any help would be appreciated. 

EDIT: The implementation from the leaked code you have mentioned, which is also I referred, is not how the current challenge is generated. This is an outdated implementation of challenge which is no longer used in csgo and many other games. You can still get challenge number generated by this unused function by sending `FF FF FF FF 57` to the server, the server will respond, but you just cannot use it to query, it’s not the same challenge system as what they are using now.

**Comment by toorisrael** [comment] 2021-11-29 23:01
Oh, ok. The problem for this gameq is I can't modify this on my csgo hosting provider. But for now I just use temp fix (no challenge). I will also try to find some more info about new challenge system when I got some time.

Also one more question - as maybe you already know, on the "internet" tab in CSGO community server browser, only real player count will show. Do you have any idea how does it work? Is server sending this info to master server, or just Valve checks how many accounts are really connected to this server?

**Comment by yourmnbbn** [comment] 2021-11-30 04:03
Well, I haven’t checked how it works on the ‘Internet’ tab in the community server browser since I use favorite tab which is more convenient to me. So far I am not sure why it act like that. I’ll take a look later.

**Comment by yourmnbbn** [comment] 2021-11-30 14:20
I've done a test for this and looks like everything displayed in the 'internet' tab of the browser is from the query except real player count. I guess this is the result requested from valve to check how many real connections are there in the server. Even fake clients won't be counted.

**Comment by toorisrael** [comment] 2021-11-30 14:33
That's true, however there are servers running with multiple IPs and player count is shown for all IPs of the sever, even tho players are connected to another IP. I'm wondering is [this](https://developer.valvesoftware.com/wiki/Master_Server_Query_Protocol) still in use for CSGO?

**Comment by yourmnbbn** [comment] 2021-11-30 14:53
I don't think this protocol has something to do with the server, the query is between game clients and steam master server. So we can't control the response without client-side tools. 

And yeah this is definitely in use in csgo but maybe not in the way that the documentation writes. They've said in the beginning:

> This page documents the legacy Steam master server query protocol. The legacy master is still used by older games and mods, but all current games and mods query the master server through Steam directly.

**Comment by toorisrael** [comment] 2021-11-30 15:01
I think it's possible this works this way:
1) server sends updates to master
2) client gets some info from master (only on internet tab), for example player count

But I may be wrong. For now I've found only this (old build with symbols):
objdump -d engine.so | grep master
000ef170 <_GLOBAL__sub_I_sv_master_share_game_socket>:
   ef24d:       e8 fc ff ff ff          call   ef24e <_GLOBAL__sub_I_sv_master_share_game_socket+0xde>
than I've checked, and this cvar:
sv_master_share_game_socket
still exists in current build, which suggests there could be some communication with master (or maybe they just left some old sh*t like always xD). I will dump some packets later to be 100% sure.

**Comment by yourmnbbn** [comment] 2021-11-30 15:26
Yeah, maybe they just stay in the binary and not used now just like the `FF FF FF FF 57` query for challenge. If this real player count is what master server got from the game server, then there must be a function to get the human player count without fake clients in the binary. This can be easily tested by detouring the function if you think you've found it. If not, the number of players is counted by the master server only, then we're done. There is nothing we can do.

So I suppose there are two ways of figuring out how this works which are relatively easy compared to other idea.
1.Find all the possible counting functions in binary and make them return false value to test.(But it's really hard to find them ALL since there are no complete symbols.)
2.Analyze the server side packets sent to the master server to see if there is information about this.(Also really hard without the protocol detail, the legacy protocol might help, but still not too easy)

**Comment by toorisrael** [comment] 2021-11-30 15:44
Also they can check how many accounts are connected to this server steamid/ip by Game Coordinator, and send this to client by master (maybe).

**Comment by yourmnbbn** [comment] 2021-11-30 16:22
There are lots of possibilities. As long as the player is counted on the game server side then changing this is possible. But I am not too optimistic about this since they can easily use the info directly from the query but they are not. My opinion is that they are doing this for two reason. One is that they want to display the real player count but what’s from the query is fake clients included. The other is that they know tools like this would send fake response, so they they just change only real client count because when searching for new servers lots of players would join the servers in which have players. So other info is not so important they just leave it there. I personally think the second reason is what drove them having made this change. 

Or maybe I am wrong, this is just because the first reason, and it has existed for a long time.

**Comment by toorisrael** [comment] 2021-11-30 22:01
I've dumped some packets, but server is communicating with Valve with TCP with TLS...
What I've also found: https://github.com/perilouswithadollarsign/cstrike15_src/blob/master/engine/sv_main.cpp#L3264
![image](https://user-images.githubusercontent.com/4301144/144136039-f6b7733a-4748-4100-a58c-c3e6b07a60cc.png)
symbols build: 55 89 E5 5D C3 90 90 90 90 90 90 90 90 90 90 90 55 89 E5 8B 45 08 C7 00 10 24 53 00 (0017a5b0)
current build: 55 89 E5 5D C3 90 90 90 90 90 90 90 90 90 90 90 55 89 E5 8B 45 08 C7 00 ?? ?? 53 00 (00176e90)
However like I mentioned I'm just a beginner at this, don't even know if I should use first or second address from objdump.

**Comment by yourmnbbn** [comment] 2021-12-01 07:56
Oh, nice work! You should use the CGameServer::UpdateMasterServerPlayers which is a override function. Using signature to detour is fine, bur since this is a virtual function I suggest using sourcehook, virtual table offset is less likely to change than signatures. If this function is pre hooked and we stop the original execution, in the browser should display 0 real players even if there are actual players in server, then it's 100% the function we are looking for.

Assuming this is the function, ofc it can be implemented in the extension, but I doubt that if it can be hacked. I'm not sure how to update fake players using steam api `BUpdateUserData` will make things work.

Currently I can think of a few ways:  
1. Send totally invalid information, don't know if they will be filtered by master server for invalid steamid.
2. Send valid steam id(If the user should be online?) but not connected to any servers, don't know if this will be filtered too. 
3. If there are real players in server, will it work by sending duplicate information of one player?

And yeah there might be other better ways, I will check it out when I got time. If you can also help to test this I would be grateful.

**Comment by toorisrael** [comment] 2021-12-01 13:40
So I've made a detour, probably not the right way (as I'm beginner at this like I said), just wondering if I can always return 0 players. The result I got surprised me - all fakes are visible as normal players on the internet now.
https://pastebin.com/6KXrdZai
![image](https://user-images.githubusercontent.com/4301144/144244528-67ed5947-a082-421a-8e4e-69eb0d3cfde2.png)
(those are all fake players)
EDIT: update - after some time and more fakes connected it shows "0/64", so I guess I did something totally wrong. I will spend some more time on this later.

**Comment by yourmnbbn** [comment] 2021-12-01 14:19
Well, I don't know what that function you are detouring via signature, but from the code you've pasted, your are doing nothing in the detour callback, you just call that original function and return what it has returned. If you want the calling function to use your return value, you just return what you want in the callback. If you don't want the original function to be called, just don't call it in the callback. So you can try returning your own value or a constant value for testing.

**Comment by yourmnbbn** [comment] 2021-12-02 14:52
Hey, I'm going to merge the new version, as a result this issue will be closed. I've opened another issue about the community server browser #4, if you find something new about it you can comment there.

**Closed as completed** 2021-12-02 15:00 UTC
